config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :exercises
  resources :workouts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :workouts do
    get '/page/:page', action: :index, on: :collection
  end
  root "workouts#index"
  get 'about', to: 'about#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
  has_many :sessions, :dependent => :destroy
  validates :name, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :exercise
  validates :weight, :reps, presence: true
end

app/models/workout.rb
class Workout < ApplicationRecord
  validates :name, presence: true
  has_many :exercises, :dependent => :destroy
  paginates_per 8
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
    @image_path = './erd.png'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[ show edit update destroy ]

  # GET /exercises or /exercises.json
  def index
    @exercises = Exercise.all.order('created_at DESC')
  end

  # GET /exercises/1 or /exercises/1.json
  def show
    @sessions = Session.where("exercise_id = #{params[:id]}").order('created_at DESC')
    @workout_id = params[:workout_id]
    @exericse = Exercise.where("id = #{params[:id]}")
    @workout = Workout.where("id = #{@exercise.id}")
    @workouts = Workout.where
  end

  # GET /exercises/new
  def new
    @workout_id = params[:workout_id]
    @workout = Workout.find(params[:workout_id])
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises or /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)
    @workout = Workout.where("id = #{@exercise.workout_id}").first

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to workout_url(@workout), notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1 or /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1 or /exercises/1.json
  def destroy
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to "/workouts/#{@exercise.workout_id}", notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercise_params
      params.require(:exercise).permit(:name, :description, :workout_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_session, only: %i[ show edit update destroy ]

  # GET /sessions or /sessions.json
  def index
    @sessions = Session.all.order('created_at DESC')
  end

  # GET /sessions/1 or /sessions/1.json
  def show
  end

  # GET /sessions/new
  def new
    @exercise_id = params[:exercise_id]
    @exercise = Exercise.find(params[:exercise_id])
    @session = Session.new
  end

  # GET /sessions/1/edit
  def edit
  end

  # POST /sessions or /sessions.json
  def create
    @session = Session.new(session_params)
    @exercise = Exercise.where("id = #{@session.exercise_id}").first

    respond_to do |format|
      if @session.save
        format.html { redirect_to exercise_url(@exercise), notice: "Session was successfully created." }
        format.json { render :show, status: :created, location: @session }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sessions/1 or /sessions/1.json
  def update
    respond_to do |format|
      if @session.update(session_params)
        format.html { redirect_to session_url(@session), notice: "Session was successfully updated." }
        format.json { render :show, status: :ok, location: @session }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessions/1 or /sessions/1.json
  def destroy
    @session.destroy

    respond_to do |format|
      format.html { redirect_to "/exercises/#{@session.exercise_id}", notice: "Session was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session
      @session = Session.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def session_params
      params.require(:session).permit(:weight, :reps, :exercise_id)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[ show edit update destroy ]

  # GET /workouts or /workouts.json
  def index
    if params[:search].blank?
      @workouts = Workout.all.order('created_at DESC').page params[:page]
    else
      @search = params[:search].downcase
      @workouts = Workout.all.where("lower(name) LIKE :search", search: "%#{@search}%").order('created_at DESC').page params[:page]
    end
  end

  # GET /workouts/1 or /workouts/1.json
  def show
    @exercises = Exercise.where("workout_id = #{params[:id]}")
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts or /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully created." }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1 or /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully updated." }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1 or /workouts/1.json
  def destroy
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url, notice: "Workout was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/about/show.html.erb
<h1>About this app</h1>
<div class="col-lg-6">
  <p>
    This application (Split) will track physical workouts for the user. The dataset below
    will model the business process by allowing a <b>Workout</b> to have many <b>Exercises</b>
    and an <b>Exercise</b> to have many <b>Sets</b>.
  </p>
  <p>
    The database will have 3 tables; <b>Workout</b>, <b>Exercise</b>, and <b>Set</b>. The columns on the
    <b>Workout</b> table will simply be <b>name :string</b> and <b>description :text</b>. A <b>Workout</b> will
    have many <b>Exercises</b> so the <b>Exercise</b> table will have a <b>workout_id</b> foreign key
    along with a <b>name :string</b> and a <b>description :text</b>. For each <b>Exercise</b> there will
    be many <b>Sets</b> so the <b>Set</b> table will have an <b>exercise_id</b> foreign key along with the
    number of <b>reps :int</b> and amount of <b>weight :int</b> (as pounds).
  </p>
  <p>
    Users will enter their own data, it won't be pulled from an external API so the data
    models will be populated by <b>Faker</b> or from a <b>.csv</b> for this project.
  </p>
</div>
<img src=<%=@image_path%> alt="Split ERD diagram">

app/views/exercises/_exercise.html.erb
<div id="<%= dom_id exercise %>">
  <h2>
    <%= exercise.name %>
  </h2>

  <p class="ms-2"><%= exercise.description %></p>
  <h4>Recent sets</h4>
  <% if @sessions.blank? %>
    <p>No sets yet</p>
  <% end %>
  <% @sessions.each do |session| %>
    <% set = "Reps: #{session.reps} Weight: #{session.weight} lbs"%>
    <div class="list-group">
      <%= link_to set, session, class: "list-group-item list-group-item-action my-1" %>
    </div>
  <% end %>
  <%= link_to 'Add set', "/sessions/new?exercise_id=#{exercise.id}", class: "btn btn-sm btn-primary my-1" %>
  <hr class="mt-2">
</div>

app/views/exercises/_form.html.erb
<%= form_with(model: exercise, class: "contents") do |form| %>
  <% if exercise.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 col-lg-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control mt-1" %>
  </div>

  <div class="my-5 col-lg-4">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "form-control mt-1" %>
  </div>

  <% if action_name == 'edit' %>
    <div class="my-5">
      <%= form.text_field :workout_id, type: 'hidden', :readonly => true %>
    </div>
  <% else %>
    <div class="my-5">
      <%= form.text_field :workout_id, value: @workout_id, type: 'hidden', :readonly => true %>
    </div>
  <% end %>


  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing exercise info</h1>

  <%= render "form", exercise: @exercise %>

</div>

app/views/exercises/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="alert alert-primary" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Exercises</h1>
    <%= link_to 'New exercise', new_exercise_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="exercises" class="min-w-full">
    <%= render @exercises %>
  </div>
</div>

app/views/exercises/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New exercise</h1>
  <%= render "form", exercise: @exercise %>
</div>

app/views/exercises/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="alert alert-primary" id="notice"><%= notice %></p>
    <% end %>

    <%= render @exercise %>

    <div class="inline-block d-flex ml-2">
      <%= link_to "Back", "/workouts/#{@exercise.workout_id}", class: "btn btn-sm btn-outline-primary mb-1 me-1" %>
      <%= link_to 'Edit', edit_exercise_path(@exercise) , class: "btn btn-sm btn-outline-primary mb-1 me-1" %>
      <%= button_to 'Delete', exercise_path(@exercise), method: :delete, class: "btn btn-sm btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light me-3">
  <div class="d-flex">
    <%= bootstrap_icon "lightning", width: 25, height: 25, fill: "#0d6efd", class: "ms-3 mt-2" %>
    <a class="navbar-brand" href=<%= workouts_path %>>Split</a>
  </div>
  <form class="form-inline">
    <%= link_to "View Workouts", workouts_path, class: "btn btn-outline-secondary" %>
    <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Split</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <main class="container mx-auto mt-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/workouts/_form.html.erb
<%= form_with(model: workout, class: "contents") do |form| %>
  <% if workout.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 col-lg-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control mt-1" %>
  </div>

  <div class="my-5 col-lg-4">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "form-control mt-1" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary mb-1" %>
  </div>
<% end %>

app/views/workouts/_workout.html.erb
<div id="<%= dom_id workout %>">
  <div class="d-flex justify-content-between">
    <%if action_name == 'show'%>
      <h2><%= workout.name %></h2>
    <%end%>
    <% if action_name != "show" %>
      <%= link_to workout.name, workout %>
      <div>
        <%= link_to 'Edit', edit_workout_path(workout), class: "btn btn-sm btn-outline-primary" %>
      </div>
    <% end %>
  </div>
  <% if action_name == "show" %>
    <p class="ms-2"><%= workout.description %></p>
    <h4>Exercises</h4>
    <% if @exercises.blank? %>
      <p>No exercises yet</p>
    <% end %>
    <% @exercises.each do |exercise| %>
      <div class="list-group">
        <%= link_to exercise.name, exercise, class: "list-group-item list-group-item-action my-1" %>
      </div>
    <% end %>
    <%= link_to 'Add exercise', "/exercises/new?workout_id=#{workout.id}", class: "btn btn-primary mt-1" %>

  <% end %>
  <hr class="mt-2">
</div>

app/views/workouts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing workout info</h1>

  <%= render "form", workout: @workout %>

  <%= link_to "Cancel", @workout, class: "btn btn-outline-primary" %>
</div>

app/views/workouts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="alert alert-primary" id="notice"><%= notice %></p>
  <% end %>

  <div class="d-flex justify-content-between mb-5">
    <h1 class="font-bold text-4xl ms-3 mt-3">Workouts</h1>
    <%= link_to 'New workout', new_workout_path, class: "btn btn-primary rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium me-3 mt-3" %>
  </div>

  <div id="workouts" class="min-w-full m-3">
    <%= form_tag(workouts_path, :method => "get", :class => "d-flex mb-4") do%>
      <%= search_field_tag :search, params[:search], placeholder: "Search workouts...", class: "form-control me-1" %>
      <%= button_tag "Search", :class => "btn btn-primary", :name => nil%>
    <% end %>
    <%= render @workouts %>
    <div class="d-flex justify-content-center"><%= paginate @workouts %></div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New workout</h1>

  <%= render "form", workout: @workout %>
</div>

app/views/workouts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="alert alert-primary" id="notice"><%= notice %></p>
    <% end %>

    <%= render @workout %>
    <div class="d-flex">
      <%= link_to "Back", workouts_path, class: "btn btn-outline-primary me-1" %>
      <%= link_to 'Edit', edit_workout_path(@workout), class: "btn btn-outline-primary me-1" %>
      <%= button_to 'Delete', workout_path(@workout), method: :delete, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>